version: '3.8'

services:
  pgpool:
    image: bitnami/pgpool:4
    ports:
      - "9999:9999"
    environment:
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=postgres
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=admin
      - PGPOOL_BACKEND_NODES=primary:5432,replica1:5432,replica2:5432,replica3:5432
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=postgres
    volumes:
      - ./pgpool.conf:/opt/bitnami/pgpool/conf/pgpool.conf
    depends_on:
      primary:
        condition: service_healthy
      replica1:
        condition: service_healthy
      replica2:
        condition: service_healthy
      replica3:
        condition: service_healthy
    networks:
      - pg-net
    healthcheck:
      test: ["CMD", "pgpool", "-nbutcher", "show", "-n"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  primary:
    image: postgres:17
    hostname: primary
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - primary-data:/var/lib/postgresql/data
      - ./init-primary.sh:/docker-entrypoint-initdb.d/init-primary.sh
    ports:
      - "5432"
    networks:
      - pg-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  replica1:
    image: postgres:17
    hostname: replica1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - replica1-data:/var/lib/postgresql/data
      - ./init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh
    depends_on:
      primary:
        condition: service_healthy
    ports:
      - "5432"
    networks:
      - pg-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  replica2:
    image: postgres:17
    hostname: replica2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - replica2-data:/var/lib/postgresql/data
      - ./init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh
    depends_on:
      primary:
        condition: service_healthy
    ports:
      - "5432"
    networks:
      - pg-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  replica3:
    image: postgres:17
    hostname: replica3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - replica3-data:/var/lib/postgresql/data
      - ./init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh
    depends_on:
      primary:
        condition: service_healthy
    ports:
      - "5432"
    networks:
      - pg-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  pg-net:
    driver: bridge

volumes:
  primary-data:
  replica1-data:
  replica2-data:
  replica3-data: